$(function() {
  $('.javascript').click(function(){
    $('.javascript-card-back').slideToggle();
    $('.javascript-card-front').slideToggle();
  });
  $('.operators').click(function(){
    $('.operators-card-back').slideToggle();
    $('.operators-card-front').slideToggle();
  });
  $('.variables').click(function(){
    $('.variables-card-back').slideToggle();
    $('.variables-card-front').slideToggle();
  });
  $('.variable-naming-conventions').click(function(){
    $('.variable-naming-conventions-card-back').slideToggle();
    $('.variable-naming-conventions-card-front').slideToggle();
  });
  $('.functions').click(function(){
    $('.functions-card-back').slideToggle();
    $('.functions-card-front').slideToggle();
  });
  $('.methods').click(function(){
    $('.methods-card-back').slideToggle();
    $('.methods-card-front').slideToggle();
  });
  $('.arguments').click(function(){
    $('.arguments-card-back').slideToggle();
    $('.arguments-card-front').slideToggle();
  });
  $('.parameters').click(function(){
    $('.parameters-card-back').slideToggle();
    $('.parameters-card-front').slideToggle();
  });
  $('.return').click(function(){
    $('.return-card-back').slideToggle();
    $('.return-card-front').slideToggle();
  });
  $('.chaining-methods').click(function(){
    $('.chaining-methods-card-back').slideToggle();
    $('.chaining-methods-card-front').slideToggle();
  });
  $('.strings').click(function(){
    $('.strings-card-back').slideToggle();
    $('.strings-card-front').slideToggle();
  });
  $('.booleans').click(function(){
    $('.booleans-card-back').slideToggle();
    $('.booleans-card-front').slideToggle();
  });
  $('.undefined').click(function(){
    $('.undefined-card-back').slideToggle();
    $('.undefined-card-front').slideToggle();
  });
  $('.nan').click(function(){
    $('.nan-card-back').slideToggle();
    $('.nan-card-front').slideToggle();
  });
  $('.escape').click(function(){
    $('.escape-card-back').slideToggle();
    $('.escape-card-front').slideToggle();
  });
  $('.alert').click(function(){
    $('.alert-card-back').slideToggle();
    $('.alert-card-front').slideToggle();
  });
  $('.comments').click(function(){
    $('.comments-card-back').slideToggle();
    $('.comments-card-front').slideToggle();
  });
  $('.jquery').click(function(){
    $('.jquery-card-back').slideToggle();
    $('.jquery-card-front').slideToggle();
  });
  $('.attributes').click(function(){
    $('.attributes-card-back').slideToggle();
    $('.attributes-card-front').slideToggle();
  });









//buttons for showing each index card.//


  $('#operators').click(function(){
    $('.javascript-card-back-card-back').hide();
    $('.javascript-card-back-card-front').hide();
    $('.operators-card-front').show();
  });
  $('.variables').click(function(){
    $('.variables-card-back').slideToggle();
    $('.variables-card-front').slideToggle();
  });
  $('.variable-naming-conventions').click(function(){
    $('.variable-naming-conventions-card-back').slideToggle();
    $('.variable-naming-conventions-card-front').slideToggle();
  });
  $('.functions').click(function(){
    $('.functions-card-back').slideToggle();
    $('.functions-card-front').slideToggle();
  });
  $('.methods').click(function(){
    $('.methods-card-back').slideToggle();
    $('.methods-card-front').slideToggle();
  });
  $('.arguments').click(function(){
    $('.arguments-card-back').slideToggle();
    $('.arguments-card-front').slideToggle();
  });
  $('.parameters').click(function(){
    $('.parameters-card-back').slideToggle();
    $('.parameters-card-front').slideToggle();
  });
  $('.return').click(function(){
    $('.return-card-back').slideToggle();
    $('.return-card-front').slideToggle();
  });
  $('.chaining-methods').click(function(){
    $('.chaining-methods-card-back').slideToggle();
    $('.chaining-methods-card-front').slideToggle();
  });
  $('.strings').click(function(){
    $('.strings-card-back').slideToggle();
    $('.strings-card-front').slideToggle();
  });
  $('.booleans').click(function(){
    $('.booleans-card-back').slideToggle();
    $('.booleans-card-front').slideToggle();
  });
  $('.undefined').click(function(){
    $('.undefined-card-back').slideToggle();
    $('.undefined-card-front').slideToggle();
  });
  $('.nan').click(function(){
    $('.nan-card-back').slideToggle();
    $('.nan-card-front').slideToggle();
  });
  $('.escape').click(function(){
    $('.escape-card-back').slideToggle();
    $('.escape-card-front').slideToggle();
  });
  $('.alert').click(function(){
    $('.alert-card-back').slideToggle();
    $('.alert-card-front').slideToggle();
  });
  $('.comments').click(function(){
    $('.comments-card-back').slideToggle();
    $('.comments-card-front').slideToggle();
  });
  $('.jquery').click(function(){
    $('.jquery-card-back').slideToggle();
    $('.jquery-card-front').slideToggle();
  });
  $('.attributes').click(function(){
    $('.attributes-card-back').slideToggle();
    $('.attributes-card-front').slideToggle();
  });
});
